about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
] 

posts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>', views.group_posts, name='group'),
    path('new/', views.new_post, name='new_post'),
    path('', views.index, name='index'),
    # Профайл пользователя
    path('<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path(
        '<str:username>/<int:post_id>/edit/', 
        views.post_edit, 
        name='post_edit'
        ),
]

users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup")
]

yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
]

about/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Группа', 
                            help_text='Выбрать группу')
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст', help_text='Заполнить')
    pub_date = models.DateTimeField('date published',
                                    auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='posts')
    group = models.ForeignKey(Group, on_delete=models.SET_NULL,
                              blank=True, null=True,
                              related_name='posts')

    def __str__(self):
       return self.text[:15]

    class Meta:
        ordering = ['-pub_date']

posts/forms.py
from django.forms import ModelForm

from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post

        fields = ['text', 'group']
        labels = {'text': 'Введите текст', 'group': 'Выберите группу'}
        help_texts = {'text': 'Заполнить', 'group':
                                  'Выбрать группу'}


class EditPostForm(ModelForm):
    class Meta:
        model = Post

        fields = ['text', 'group']
        labels = {'text': 'Введите текст', 'group': 'Выберите группу'}
        help_texts = {'text': 'Заполнить', 'group':
                                  'Выбрать группу'}

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):

        model = User

        fields = ("first_name", "last_name", "username", "email")

about/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    # В переменной template_name обязательно указывается имя шаблона,
    # на основе которого будет создана возвращаемая страница
    template_name = 'about/author.html'

class AboutTechView(TemplateView):
    # В переменной template_name обязательно указывается имя шаблона,
    # на основе которого будет создана возвращаемая страница
    template_name = 'about/tech.html'

posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.core.paginator import Paginator
from django.contrib.auth import get_user_model

from .forms import PostForm, EditPostForm
from .models import Group, Post

User = get_user_model()

def index(request):
    post_list = Post.objects.select_related('group').order_by('-pub_date')
    # Показывать по 10 записей на странице.
    paginator = Paginator(post_list, 10) 

    # Из URL извлекаем номер запрошенной страницы - это значение параметра page
    page_number = request.GET.get('page') 

    # Получаем набор записей для страницы с запрошенным номером
    page = paginator.get_page(page_number) 
    return render(
         request,
         'posts/index.html',
         {'page': page,}
     ) 


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts_list = Post.objects.filter(group=group).select_related('group').order_by('-pub_date')
    paginator = Paginator(posts_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number) 
    return render(request, 'group.html', {'group': group, 'page': page})



def profile(request, username): 
    author = User.objects.get(username=username)
    post_list = author.posts.all()
    #author = get_object_or_404(Post, username=author)
    #post_list = author.objects.select_related('author').order_by('-pub_date')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'page': page,
        'author': author,
        'paginator': paginator.count,
    }
    return render(request, 'profile.html', context)
        #return render(request, 'profile.html', {})
 
 
def post_view(request, username, post_id):
        author = User.objects.get(username=username)
        post = get_object_or_404(Post, id=post_id, author=author)
        #post = Post.objects.filter(author=author).filter(id=post_id).order_by('-pub_date')
        #post = Post.objects.get(id=post_id)
        count = Post.objects.filter(author=author).select_related('author').count()
        return render(request, 'post.html', {'post': post, 'author': author, 'count': count})


@login_required
def post_edit(request, username, post_id):    
    user = User.objects.filter(username=username)[0]
    #post = Post.objects.filter(id=post_id).filter(author=user)[0]
    post = get_object_or_404(Post, id=post_id, author=user)
    if user != request.user:
        return redirect('post', username=user, post_id=post_id)
    form = PostForm(request.POST or None, 
        initial={
            'text': post.text,
            'group': post.group,
        }
    )
    if form  == request.GET or not form.is_valid():
        return render(
            request, 
            'posts/new_post.html',
            {                
                'form': form,
                'button': 'Редактировать',
                'group': post,
            }
        )           
    form = PostForm(request.POST, instance=post)
    form.save()
    return redirect('post', username=user, post_id=post_id)


def new_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()

            return redirect('index')

        return render(request, 'posts/new_post.html', {'form': form})

    form = PostForm()
    return render(request, 'posts/new_post.html', {'form': form})

users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy("signup")
    template_name = "users/signup.html"

templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
{% load user_filters %}
  <main role="main" class="container">
      <div class="row">
          <!-- Левый вспомогательный блок -->
          <div class="col-md-3 mb-3 mt-1">
              <div class="card">
                  <div class="card-body">
                      <ul class="list-group list-group-flush">
                          <li class="list-group-item">
                              <div class="h3">
                                  Об авторе
                              </div> 
                          </li>
                          <li class="list-group-item">
                              <div class="h6 text-muted">
                                  Привет! Меня зовут Даня. Это мой самый первый сайт
                              </div>
                          </li>
                      </ul>                                               
                  </div>                    
              </div>                
          </div>
          <!-- Тело страницы -->
          <div class="col-md-9">
              <div class="card-body">                    
                  <div class="card-text">
                      <p>С программированием на Python я познакомился во время учебы в институте.<br>
                      Сейчас продолжаю изучать данный язык программирования на платформе Яндекс.Практикум<br>
                      Хочу стать востребованным специалистом в данной области<br>
                      <a href="https://github.com/dansen95">Здесь</a>, ссылка на мой аккаунт на GitHub<br>
                      Я во время прохождения курса:<br>
                      <img src="http://wallpoper.com/images/00/14/97/24/cute-golden-kitten_00149724.jpg" alt="Lamp" width="500" height="320">
                      </p>
                  </div>                    
              </div>                
          </div>            
      </div>        
  </main>
{% endblock %}

templates/about/tech.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
{% load user_filters %}
  <main role="main" class="container">
      <div class="row">
          <!-- Левый вспомогательный блок -->
          <div class="col-md-3 mb-3 mt-1">
              <div class="card">
                  <div class="card-body">
                      <ul class="list-group list-group-flush">
                          <li class="list-group-item">
                              <div class="h3">
                                  О сайте
                              </div> 
                          </li>
                          <li class="list-group-item">
                              <div class="h6 text-muted">
                                  Данный сайт полностью написан на Django, фреймворке для языка программирования Python
                              </div>
                          </li>
                      </ul>                                               
                  </div>                    
              </div>                
          </div>
          <!-- Тело страницы -->
          <div class="col-md-9">
              <div class="card-body">                    
                  <div class="card-text">
                      <p><a href="https://docs.djangoproject.com/">Ссылка</a> на официальную документацию по Django</p>
                  </div>                    
              </div>                
          </div>            
      </div>        
  </main>
{% endblock %}

templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</head>

<body>
    {% include 'nav.html' %}
    <main>
        <div class="container">
            {% block header %}<h1>The Last Social Media You'll Ever Need</h1>{% endblock %}
            {% block content %}
            <!-- Содержимое страницы -->
            {% endblock %}
        </div>
    </main>
    {% include 'footer.html' %}
</body>

</html> 

templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">
        <a href="{% url 'about:author' %}">Об авторе</a>
        <a href="{% url 'about:tech' %}">О сайте</a>
    </p>
    <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube © {% now 'Y' %}, все права защищены.</p>
</footer> 

templates/group.html
{% extends "base.html" %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block header %}
<h1>{{ group.title }}</h1>
{% endblock %}
{% block content %}
<p>{{ group.description }}</p>
{% for post in page %}
<h3>
Автор: {{ post.author.get_full_name }}, дата публикации: {{ post.pub_date|date:"d M Y" }}
</h3>
<p>{{ post.text|linebreaksbr }}</p>
<hr>
{% endfor %}
{% include "paginator.html" %}
{% endblock %}

templates/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="/"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        Пользователь: {{ user.username }}.
        <a class="p-2 text-dark" href="{% url 'new_post' %}">Новая запись</a>
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav> 

templates/paginator.html
{# Отрисовываем навигацию паджинатора только если есть и другие страницы #}
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %} 

templates/post.html
{% extends "base.html" %}
{% block title %} Страница поста {% endblock %}
{% block header %} Последние обновления на сайте {% endblock %}
{% block content %}
<main role="main" class="container">
    <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                <div class="card">
                        <div class="card-body">
                                <div class="h2">
                                    <!-- Имя автора -->
                                    {{ author.get_full_name }}
                                </div>
                                <div class="h3 text-muted">
                                     <!-- username автора -->
                                     {{ author }}
                                </div>
                        </div>
                        <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                        <div class="h6 text-muted">
                                        Подписчиков: XXX <br />
                                        Подписан: XXX
                                        </div>
                                </li>
                                <li class="list-group-item">
                                        <div class="h6 text-muted">
                                            <!--Количество записей -->
                                            Записей: {{ count }}
                                        </div>
                                </li>
                        </ul>
                </div>
        </div>

        <div class="col-md-9">
            
            
            <!-- Пост -->  
                <div class="card mb-3 mt-1 shadow-sm">
                        <div class="card-body">
                                <p class="card-text">
                                        <!-- Ссылка на страницу автора в атрибуте href; username автора в тексте ссылки -->
                                        <a href="/{{ author }}/"><strong class="d-block text-gray-dark">{{ author }}</strong></a>
                                        <!-- Текст поста -->
                                        {{ post.text|linebreaksbr }}
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group ">
                                                <!-- Ссылка на редактирование, показывается только автору записи -->
                                                <a class="btn btn-sm text-muted" href="/{{ author }}/{{ post.id }}/edit" role="button">Редактировать</a>
                                        </div>
                                        <!-- Дата публикации  -->
                                        <small class="text-muted">{{ posts.pub_date|date:"d M Y" }}</small>
                                </div>
                        </div>
                </div>
                
     </div>
    </div>
</main> 
{% endblock %}

templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления | Yatube{% endblock %}
<h1>{% block header %}Последние обновления на сайте{% endblock %}</h1>
{% block content %}
{% for post in page %}
<h3>
Автор: {{ post.author.get_full_name }}, дата публикации: {{ post.pub_date|date:"d M Y" }}
</h3>
<p>{{ post.text|linebreaksbr }}</p>
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include "paginator.html" %}
{% endblock %}

templates/posts/new_post.html
{% extends "base.html" %}
{% block title %}Новая запись{% endblock %}
{% load user_filters %}
{% block content%}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Создание новой записи</div>
            <div class="card-body">
              
                {% for error in form.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                 {% endfor %}

                <form method="POST">
                {% csrf_token %}
        
                {% for field in form %}
                    <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                        <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                            <div class="col-md-6">

                                {{ field|addclass:"form-control" }}

                                {% if field.help_text %}
                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                {% endif %}
                            </div>                
                    </div>
                {% endfor %}

                    <div class="col-md-6 offset-md-4">     
                            <button type="submit" class="btn btn-primary">
                                Отправить
                            </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% block title %} Страница пользователя {{ username.get_full_name }} {% endblock %}
{% block header %} Последние обновления на сайте {% endblock %}
{% block content %}

<main role="main" class="container">
    <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                

                
                    <div class="card">
                            <div class="card-body">
                                    <div class="h2">
                                        <!-- Имя автора -->
                                        {{ author.get_full_name }}
                                    </div>
                                    <div class="h3 text-muted">
                                         <!-- username автора -->
                                         {{ author }}
                                    </div>
                            </div>
                            <ul class="list-group list-group-flush">
                                    <li class="list-group-item">
                                            <div class="h6 text-muted">
                                            Подписчиков: XXX <br />
                                            Подписан: XXX
                                            </div>
                                    </li>
                                    <li class="list-group-item">
                                        
                                            <div class="h6 text-muted">
                                                <!-- Количество записей -->
                                                Записей: {{ paginator }}
                                            </div>
                                            
                                    </li>
                            </ul>
                    </div>
            </div>
            
            <div class="col-md-9">                
                {% for post in page %}
                <!-- Начало блока с отдельным постом --> 
                    <div class="card mb-3 mt-1 shadow-sm">
                            <div class="card-body">
                                    <p class="card-text">
                                            <!-- Ссылка на страницу автора в атрибуте href; username автора в тексте ссылки -->
                                            <a href="/{{ author }}/"><strong class="d-block text-gray-dark">{{ author }}</strong></a>
                                            <!-- Текст поста -->
                                            {{ post.text|linebreaksbr }}
                                    </p>
                                    <div class="d-flex justify-content-between align-items-center">
                                            <div class="btn-group ">
                                                    <!-- Ссылка на страницу записи в атрибуте href-->
                                                    <a class="btn btn-sm text-muted" href="/{{ author }}/{{ post.id }}/" role="button">Добавить комментарий</a>
                                                    <!-- Ссылка на редактирование, показывается только автору записи -->
                                                    <a class="btn btn-sm text-muted" href="/{{ author }}/{{ post.id }}/edit" role="button">Редактировать</a>
                                            </div>
                                            <!-- Дата публикации  -->
                                            <small class="text-muted">{{ post.pub_date|date:"d M Y" }}</small>
                                    </div>
                            </div>
                    </div>
                <!-- Конец блока с отдельным постом --> 
                
                <!-- Остальные посты -->  
                {% endfor %}
                
                
                <!-- Здесь постраничная навигация паджинатора -->
                {% include "paginator.html" %}
                
     </div>
    </div>
</main> 

{% endblock %}

users/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Зарегистрироваться</div>
            <div class="card-body">
                
                {% for error in form.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error|escape }}
                    </div>
                {% endfor %}

                <form method="post" action="{% url 'signup' %}">
                {% csrf_token %}

                {% for field in form %}
                    <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                            <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                            <div class="col-md-6">

                                {{ field|addclass:"form-control" }}

                                {% if field.help_text %}
                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                {% endif %}
                            </div>                
                    </div>
                {% endfor %}

                    <div class="col-md-6 offset-md-4">              
                            <button type="submit" class="btn btn-primary">
                                Зарегистрироваться
                            </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %} 